# Generated by Django 3.1.7 on 2022-05-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
