# Generated by Django 3.1.7 on 2022-05-01 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='last name')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, choices=[(True, 'Male'), (False, 'Female'), (None, 'Not selected')], default=None, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=utils.upload.profile_image_upload, validators=[utils.validators.validate_image_size, utils.validators.validate_image_format])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'unique_together': {('user', 'first_name', 'last_name')},
            },
        ),
    ]
