# Generated by Django 3.1.7 on 2022-05-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_auto_20220501_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_staff'),
        ),
    ]
