# Generated by Django 3.1.7 on 2022-05-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediateka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='name',
            field=models.CharField(default='vJomcn0FbqY3lioBM7wU', max_length=50),
        ),
    ]
