# Generated by Django 3.1.7 on 2022-05-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220503_2159'),
        ('mediateka', '0002_auto_20220503_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='name',
            field=models.CharField(default='nDq96cRIgjNF0tj0felX', max_length=50),
        ),
        migrations.RemoveField(
            model_name='playlists',
            name='track',
        ),
        migrations.AddField(
            model_name='playlists',
            name='track',
            field=models.ManyToManyField(related_name='Tracks', to='main.Tracks'),
        ),
    ]
